[package]
name = "lunatic"
version = "0.6.2"
edition = "2018"
authors = ["Bernard Kolobara <bernard@lunatic.solutions>"]
description = "This library contains higher level wrappers for low level Lunatic syscalls."
license = "Apache-2.0/MIT"
readme = "Readme.md"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
thiserror = "1.0"
serde = { version = "1.0", features = ["derive"] }
rmp-serde = "0.15"
lunatic-macros = { version = "^0.6.1", path = "./lunatic-macros" }

[workspace]
members = [
  "lunatic-macros"
]