[package]
name = "lunatic"
version = "0.3.9"
authors = ["Bernard Kolobara <me@kolobara.com>"]
edition = "2018"
description = "This library contains higher level wrappers for low level Lunatic syscalls."
license = "Apache-2.0/MIT"
readme = "Readme.md"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
anyhow = "1.0"
thiserror = "1.0"
serde = { version = "1.0", features = ["derive"] }
bincode= "1.3"

[dev-dependencies]
criterion = "0.3"

[[bench]]
name = "lunatic_benchmark"
harness = false
